# Generated by Django 2.2.6 on 2019-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Midia',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
