# Generated by Django 2.2.6 on 2019-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_midia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Midia',
            field=models.TextField(),
        ),
    ]
