# Generated by Django 2.2.6 on 2019-11-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191127_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Midia',
            field=models.CharField(max_length=100),
        ),
    ]
